
/* Populate tabla libros */
-- INSERT INTO libros (cantidad, create_at, imagen, nombre, precio) VALUES(0, NOW(),'http://resumiendolo.com/wp-content/uploads/2018/02/harry-potter-y-la-piedra-filosofal-1-602x1024.jpg', 'Harry Potter y la piedra filosofal', 120090);
--INSERT INTO libros (cantidad, create_at, imagen, nombre, precio) VALUES(5, NOW(),'http://resumiendolo.com/wp-content/uploads/2018/02/Harry-Potter-y-la-c%C3%A1mara-secreta-4-e1518549159273.jpg', 'Harry Potter y la cámara secreta', 59990);
-- INSERT INTO libros (cantidad, create_at, imagen, nombre, precio) VALUES(7, NOW(),'https://imagessl0.casadellibro.com/a/l/t5/30/9788498383430.jpg', 'Harry Potter y el prisionero de Azkaban', 25990);
-- INSERT INTO libros (cantidad, create_at, imagen, nombre, precio) VALUES(0, NOW(),'https://imagessl1.casadellibro.com/a/l/t5/21/9788498383621.jpg', 'Harry Potter y la Orden del Fénix', 259990);
-- INSERT INTO libros (cantidad, create_at, imagen, nombre, precio) VALUES(4, NOW(),'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBAbY6Ny3dCE8ifkIZaA6c73SBSOBzxnNuWopBtPdj5_Ga3cVF&s', 'Harry Potter y el misterio del príncipe', 259990);
-- INSERT INTO libros (cantidad, create_at, imagen, nombre, precio) VALUES(2, NOW(),'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWdSl-YGQrXCS0Uvta1nF3QaLrZWIBtnqkrk7sV2QmzFNBhh61&s', 'Harry Potter y las Reliquias de la Muerte', 259990);
-- INSERT INTO libros (cantidad, create_at, imagen, nombre, precio) VALUES(6, NOW(),'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCWKh5inq1ATeQy0H5YMqbWfClvjc5MTe9Whpb55wi3mfb1j4zog&s', 'Harry Potter y el legado maldito', 30990);
-- INSERT INTO libros (cantidad, create_at, imagen, nombre, precio) VALUES(4, NOW(),'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR675fd5cB3LtBOcRTHH8nc1oOeNRtGQkBW-_7VNImkrcihg4Ay&s', 'Animales fantásticos y dónde encontrarlos', 259990);
--
-- /*
-- INSERT INTO libros (cantidad, create_at, imagen, nombre, precio) VALUES(1, NOW(),'imagen', 'Quidditch a través de los tiempos', 259990);
-- INSERT INTO libros (cantidad, create_at, imagen, nombre, precio) VALUES(9, NOW(),'imagen', 'Los cuentos de Beedle el Bardo', 12990);
-- INSERT INTO libros (cantidad, create_at, imagen, nombre, precio) VALUES(12, NOW(),'imagen', 'Hogwarts: la guía incompleta y poco fiable', 259990);
-- INSERT INTO libros (cantidad, create_at, imagen, nombre, precio) VALUES(0, NOW(),'imagen', 'Short Stories from Hogwarts of Heroism, Hardship and Dangerous Hobbies', 259990);
-- INSERT INTO libros (cantidad, create_at, imagen, nombre, precio) VALUES(4, NOW(),'imagen', 'Hogwarts of Power, Politics and Pesky Poltergeist', 259990);
-- */
--
-- --Creamos dos usuarios con sus roles
--  INSERT INTO users (username, password, enabled) VALUES('eduard','$2a$10$O9wxmH/AeyZZzIS09Wp8YOEMvFnbRVJ8B4dmAMVSGloR62lj.yqXG','1');
--  INSERT INTO users (username, password, enabled) VALUES('admin','$2a$10$DOMDxjYyfZ/e7RcBfUpzqeaCs8pLgcizuiQWXPkU35nOhZlFcE9MS','1');
--
-- INSERT INTO authorities (user_id, authority) VALUES (1,'ROLE_USER');
-- INSERT INTO authorities (user_id, authority) VALUES (2,'ROLE_ADMIN');
-- INSERT INTO authorities (user_id, authority) VALUES (2,'ROLE_USER');
--
-- /* Populate tables */
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Andres', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-01', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('John', 'Doe', 'john.doe@gmail.com', '2017-08-02', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2017-08-03', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Jane', 'Doe', 'jane.doe@gmail.com', '2017-08-04', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2017-08-05', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2017-08-06', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2017-08-07', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2017-08-08', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2017-08-09', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('James', 'Gosling', 'james.gosling@gmail.com', '2017-08-010', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Bruce', 'Lee', 'bruce.lee@gmail.com', '2017-08-11', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Johnny', 'Doe', 'johnny.doe@gmail.com', '2017-08-12', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('John', 'Roe', 'john.roe@gmail.com', '2017-08-13', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Jane', 'Roe', 'jane.roe@gmail.com', '2017-08-14', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Richard', 'Doe', 'richard.doe@gmail.com', '2017-08-15', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Janie', 'Doe', 'janie.doe@gmail.com', '2017-08-16', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Phillip', 'Webb', 'phillip.webb@gmail.com', '2017-08-17', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Stephane', 'Nicoll', 'stephane.nicoll@gmail.com', '2017-08-18', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Sam', 'Brannen', 'sam.brannen@gmail.com', '2017-08-19', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Juergen', 'Hoeller', 'juergen.Hoeller@gmail.com', '2017-08-20', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Janie', 'Roe', 'janie.roe@gmail.com', '2017-08-21', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('John', 'Smith', 'john.smith@gmail.com', '2017-08-22', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Joe', 'Bloggs', 'joe.bloggs@gmail.com', '2017-08-23', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('John', 'Stiles', 'john.stiles@gmail.com', '2017-08-24', '');
-- INSERT INTO clientes (nombres, apellidos, email, create_at, foto) VALUES('Richard', 'Roe', 'stiles.roe@gmail.com', '2017-08-25', '');
